version: '3.4'

services:
  rabbitmq-service:
    image: hansehe/rabbitmq-mqtt:latest
    hostname: rabbitmq-service
    secrets:
      - site.crt
      - site.ca
      - site.key
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
      - 15673:15673
      - 15675:15675
      - 8883:8883
      - 1883:1883
    configs:
      - source: rabbitmq.ssl.conf
        target: /etc/rabbitmq/rabbitmq.conf
    environment:
      RABBITMQ_NODENAME: rabbit
    networks:
      - backend_network

networks:
  backend_network:
    external: true

secrets:
  site.crt:
    external: true
  site.ca:
    external: true
  site.key:
    external: true

configs:
  rabbitmq.ssl.conf:
    external: true